// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/calculator": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HealthCalculator"
                ],
                "summary": "Return IAM and Calc",
                "parameters": [
                    {
                        "description": "Health Information",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/calculator.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/calculator.Response"
                        }
                    }
                }
            }
        },
        "/healthcheck": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Healthcheck"
                ],
                "summary": "Return 200 status Ok in healthcheck",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/healthcheck.Response"
                        }
                    }
                }
            }
        },
        "/liveness": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "liveness"
                ],
                "summary": "Return 200 status Ok in liveness",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/liveness.Response"
                        }
                    }
                }
            }
        },
        "/readiness": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "readiness"
                ],
                "summary": "Return 200 status Ok in readiness",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/readiness.Response"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Version"
                ],
                "summary": "Return 200 status Get in version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/version.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "calculator.Request": {
            "type": "object",
            "required": [
                "activity_intensity",
                "age",
                "gender",
                "height",
                "weight"
            ],
            "properties": {
                "activity_intensity": {
                    "type": "string"
                },
                "age": {
                    "type": "integer"
                },
                "gender": {
                    "type": "string"
                },
                "height": {
                    "type": "number"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "calculator.Response": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "basal": {
                    "type": "object",
                    "properties": {
                        "bmr": {
                            "type": "object",
                            "properties": {
                                "unit": {
                                    "type": "string"
                                },
                                "value": {
                                    "type": "number"
                                }
                            }
                        },
                        "necessity": {
                            "type": "object",
                            "properties": {
                                "unit": {
                                    "type": "string"
                                },
                                "value": {
                                    "type": "number"
                                }
                            }
                        }
                    }
                },
                "health_info": {
                    "type": "object",
                    "properties": {
                        "activity_intensity": {
                            "type": "string"
                        },
                        "age": {
                            "type": "integer"
                        },
                        "gender": {
                            "type": "string"
                        },
                        "height": {
                            "type": "number"
                        },
                        "weight": {
                            "type": "number"
                        }
                    }
                },
                "imc": {
                    "type": "object",
                    "properties": {
                        "class": {
                            "type": "string"
                        },
                        "result": {
                            "type": "number"
                        }
                    }
                },
                "recomendations": {
                    "type": "object",
                    "properties": {
                        "calories": {
                            "type": "object",
                            "properties": {
                                "gain_weight": {
                                    "type": "object",
                                    "properties": {
                                        "unit": {
                                            "type": "string"
                                        },
                                        "value": {
                                            "type": "number"
                                        }
                                    }
                                },
                                "loss_weight": {
                                    "type": "object",
                                    "properties": {
                                        "unit": {
                                            "type": "string"
                                        },
                                        "value": {
                                            "type": "number"
                                        }
                                    }
                                },
                                "maintain_weight": {
                                    "type": "object",
                                    "properties": {
                                        "unit": {
                                            "type": "string"
                                        },
                                        "value": {
                                            "type": "number"
                                        }
                                    }
                                }
                            }
                        },
                        "protein": {
                            "type": "object",
                            "properties": {
                                "unit": {
                                    "type": "string"
                                },
                                "value": {
                                    "type": "integer"
                                }
                            }
                        },
                        "water": {
                            "type": "object",
                            "properties": {
                                "unit": {
                                    "type": "string"
                                },
                                "value": {
                                    "type": "number"
                                }
                            }
                        }
                    }
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "healthcheck.Response": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "integer"
                }
            }
        },
        "liveness.Response": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "integer"
                }
            }
        },
        "readiness.Response": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "version.Response": {
            "type": "object",
            "required": [
                "application",
                "version"
            ],
            "properties": {
                "application": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
